fluentify/src/api/google.js, fluentify/src/api/openai.js, fluentify/src/api/openai.test.js
It tests if with a given "very hard" difficulty, the function returns an error message as expected
=> Unit test for generatetText function added

fluentify/src/components/GenerateText.jsx, fluentify/src/components/Or.jsx, fluentify/src/components/SelectFile.jsx
- align the height of selectFile and generateText section
- add a show filename section after file is uploaded
- adjust the or part
=> adjust layout

fluentify/src/components/MainHeader.jsx
-added a Typewriter effect for the title part
=> add animation to the title part #51

fluentify/src/components/MainHeader.jsx
Fix the bug that last letter won't show in the previous version
=> update the animation #51

fluentify/src/components/SelectFile.jsx
Added a placeholder and color indication of selected file
=> indicate filename #61

fluentify/src/SecondPage.jsx, fluentify/src/components/MainPageModal.jsx, fluentify/src/main.jsx
- created a mock second page
- add router and link from main to second page
=> add page navigation from main to second #67

fluentify/src/App.jsx, fluentify/src/components/GenerateText.jsx, fluentify/src/components/Instruction.jsx, fluentify/src/components/InstructionModal.jsx, fluentify/src/components/MainHeader.jsx, fluentify/src/components/SelectFile.jsx
- Create an instruction button on the main page
- Adjust the layout of the main page so that the vertical line is placed in the middle
- Create an instruction modal
- Integrate the modal with App.jsx and MainHeader.jsx to make the function work
=> Create instruction button and instruction modal, make integration #63

.github/workflows/ci.yml, fluentify/src/SecondPage.jsx, fluentify/src/components/TranslatedText.jsx
=> Second Page

fluentify/src/SecondPage.jsx, fluentify/src/context/LanguageContext.jsx
uses translate function to set translatedText and sourceLanguage
=> integrate translate function #77

fluentify/src/App.jsx, fluentify/src/components/InstructionModal.jsx, fluentify/src/components/SelectFile.jsx
Please review the instruction content. Let me know if you need changes.
=> Website instruction

fluentify/src/api/google.test.js, fluentify/src/api/openai.test.js
- changed import statements
- changed mock functions
=> Fix unit tests

fluentify/src/components/TranslatedText.jsx
=> Display translated text to box #98

fluentify/package-lock.json, fluentify/package.json, fluentify/src/integ-tests/setup.js, fluentify/vite.config.js
Closes #106 
for integration testing behaviour of features
=> Configure React Testing Library with Vitest 

fluentify/src/components/QuizDisplay.test.jsx
- added integration test for success case of quiz generation
- added integration test for error case of quiz generation
=> Quiz integration test

fluentify/src/App.jsx, fluentify/src/SecondPage.jsx, fluentify/src/components/GenerateText.jsx, fluentify/src/components/QuizDisplay.jsx, fluentify/src/components/SelectFile.jsx, fluentify/src/components/Spinner.jsx, fluentify/src/components/TranslatedText.jsx
- added loading status indicator for: generating text, reading file, translating, generating quiz
- displayed error on second page
=> Status indicators

fluentify/src/SecondPage.jsx, fluentify/src/components/QuizDisplay.jsx
=> fixed layout of page 2 #136

fluentify/src/SecondPage.jsx, fluentify/src/components/GenerateText.jsx, fluentify/src/components/QuizDisplay.jsx, fluentify/src/components/QuizDisplay.test.jsx, fluentify/src/components/SelectFile.jsx
- changed error messages given to users
=> changed the error messages to be more user friendly #112

fluentify/cypress.config.js, fluentify/cypress/e2e/cypress-integration-tests/spec.cy.js, fluentify/cypress/fixtures/example.json, fluentify/cypress/support/commands.js, fluentify/cypress/support/e2e.js, fluentify/package-lock.json, fluentify/package.json
- install cypress
- changes package.json file to avoid conflict with vitest
=> cypress set up #142

fluentify/src/api/detectLanguage.js, fluentify/src/components/SelectFile.jsx
- added language detection function
- integrated language detection function to SelectFile component
=> added language detection function #141

.github/workflows/ci-cd.yml, fluentify/src/components/SelectFile.test.jsx
=> Fix unit test selectfile

fluentify/cypress/e2e/cypress-integration-tests/generateText.cy.js, fluentify/cypress/e2e/cypress-integration-tests/spec.cy.js
Case 1: click easy button
Expected: correct modal shows up
Case 2: click medium button
Expected: correct modal shows up
Case 3: click hard button
Expected: correct modal shows up
=> generate text feature tests, 3 scenarios #122

fluentify/src/components/MainPageModal.jsx, fluentify/src/components/QuizDisplay.jsx, fluentify/src/components/SelectFile.jsx, fluentify/src/context/LanguageContext.jsx, fluentify/src/data/languages.json
- show right answer on wrong choice
- score
- fixed first quiz question from previous selection bug
- fixed error on refresh page
- added remember last language selection for heuristics
- show detected language
- grey out submit
=> Quiz state

fluentify/src/App.jsx, fluentify/src/SecondPage.jsx, fluentify/src/components/GenerateText.jsx, fluentify/src/components/MainHeader.jsx, fluentify/src/components/Or.jsx, fluentify/src/components/QuizDisplay.jsx, fluentify/src/components/SelectFile.jsx, fluentify/src/components/TranslatedText.jsx
- adjust 1st page component height
- adjust second page component height
- adjust buttons layout
=> Fix layout #126

fluentify/src/components/QuizDisplay.jsx
=> Changed quiz box border

fluentify/src/api/detectLanguage.js, fluentify/src/api/detectLanguage.test.js, fluentify/src/api/getTextFromFile.test.js
- unit tests for detectLanguage function
- unit tests for getTextFromFile function
=> Google unit tests

fluentify/cypress/e2e/cypress-integration-tests/generateText.cy.js, fluentify/cypress/e2e/cypress-integration-tests/translateFeature.cy.js
=> Translate feature

fluentify/src/App.test.jsx, fluentify/src/components/SelectFile.test.jsx
=> add integration tests for detecting language #160
